spring:
  application:
    name: orderservice
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog-master.yml
jwt:
  secret:
    access: ${JWT_SECRET_ACCESS}
    refresh: ${JWT_SECRET_REFRESH}

logging:
  level:
    root: info
  file:
    name: logs/application.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [traceId:%X{traceId}] %-5p %c{1}:%L - %m%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [traceId:%X{traceId}] %-5p %c{1}:%L - %m%n"